export const LOGIN = 'CONNECT'
export const LOGOUT = 'LOGOUT'

export const CHANGE_USER_NAME = 'CHANGE_USER_NAME'

export const LOAD_PROFILE = 'LOAD_PROFILE'
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS'
export const LOAD_PROFILE_FAILURE = 'LOAD_PROFILE_FAILURE'

export const LOAD_CUSTOMERS = 'LOAD_CUSTOMERS'
export const LOAD_CUSTOMERS_SUCCESS = 'LOAD_CUSTOMERS_SUCCESS'
export const LOAD_CUSTOMERS_FAILURE = 'LOAD_CUSTOMERS_FAILURE'

export const LOAD_ORDERS = 'LOAD_ORDERS'
export const LOAD_ORDERS_SUCCESS = 'LOAD_ORDERS_SUCCESS'
export const LOAD_ORDERS_FAILURE = 'LOAD_ORDERS_FAILURE'
