const VANILLA_REDUX = 0
const REDUX_TOOLBELT = 1
const REDUX_TOOLBELT_THUNK = 2
const REDUX_TOOLBELT_SAGA = 3
const VANILLA_REDUX_SAGA = 4

export const REDUX_STYLE_TYPES = {
  VANILLA_REDUX, REDUX_TOOLBELT, REDUX_TOOLBELT_THUNK,
  REDUX_TOOLBELT_SAGA, VANILLA_REDUX_SAGA
}

export const REDUX_STYLE_TYPES_NAMES = {
  [VANILLA_REDUX]: 'Vanilla Redux',
  [REDUX_TOOLBELT]: 'Redux Toolbelt',
  [REDUX_TOOLBELT_THUNK]: 'Redux Toolbelt Thunk',
  [REDUX_TOOLBELT_SAGA]: 'Redux Toolbelt Saga',
  [VANILLA_REDUX_SAGA]: 'Vanilla With Saga'
}
